### ISSUE TITLE
Remove Python wrapper class initialization procedures

### ISSUE THREAD

**Issue by cur33** [ghamerly/fast-kmeans#18]
The method of struct initialization recommended by the Python/C API docs is
      to use C99 designated initializers, which are very useful but not available
      in C++. Instead, I followed this approach:

- for structs with sufficiently few attributes, like PyModuleDef, I used a standard initialization approch by providing values for all members (except trailing ones)
- for structs with many attributes, like PyTypeObject, I created init_*_members() procedures that would set only the needed members, which are called in the PyInit_fastkmeans() function

However, having seen other extension modules such as those in numpy which simply provide 0 or NULL values for all unused struct members, I'm starting to think that might just be simpler and more maintainable than I'd originally thought.

**Comment by ghamerly** [comment]
This should be fixed in #20 but I have not dug enough to determine that. @cur33 please close this if it's fixed.

**Comment by cur33** [comment]
Yes, this is fixed too. Even though the long lists of NULL values (with the attribute name in comments) still bugs me, I think it's a little cleaner than my previous approach, and it should make it easy to see what attributes could be added in the future, if so desired.
