### ISSUE TITLE
Move Python wrapper files to new directory

### ISSUE THREAD

**Issue by cur33** [ghamerly/fast-kmeans#19]
Since the original structure of the project merely contained all the source files in the `src` directory, I kept it that way, but now that the number of files has increased quite a bit, it might make more sense to move the Python module files into a separate directory. This shouldn't create a problem for the Python module to find the header files of the C++ classes and functions, because the setup.py file can just be altered to set the `include_dir` keyword argument to be something like '..' instead of '.'.

**Comment by ghamerly** [comment]
Fixed in #20
