### ISSUE TITLE
Some problem in elkan‘s implement

### ISSUE THREAD

**Issue by Etherious** [ghamerly/fast-kmeans#22]
![image](https://user-images.githubusercontent.com/16865299/49328639-2134f200-f5af-11e8-8d3c-8aa11556263b.png)

**Comment by ghamerly** [comment]
@Etherious thanks for the bug report; can you provide the input you used and command-line parameters you used to run this so that we can reproduce and debug it?

**Comment by Etherious** [comment]
@ghamerly Oh sorry, I forgot this.
This problem was happened when I run the sampleScript.py which is in the python-bindings

**Comment by ghamerly** [comment]
Thank you, I can replicate this, it is indeed an issue.

@cur33 do you have any ideas here?

**Comment by cur33** [comment]
Apparently I commented out a line in `py_elkan.cpp` and never replaced it with the correct line. Whoops. I'll submit a pull request with the correction.

**Comment by cur33** [comment]
#23 fixes the problem in my testing.
